"""Project Euler - Problem 2 solution:

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

I'm not sure this is really a map-reduceable problem, since there's no real mapping to be done"""

# generator
def fib(n):
    a, b = 0, 1
    while a < n:
        yield a
        a, b = b, a + b

total = 0

for i in fib(4000000 - 1):
    if not i % 2:
        total += i

print total